#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Describes args for a command that requires a champion ID.
    /// </summary>
    public class ChampionCommandArgs {
        
        /// <summary>
        /// ID of a champion that should be hovered upon, picked or banned.
        /// </summary>
        [JsonProperty("championId")]
        public int ChampionId { get; set; } = default!;
    }
}

#nullable restore
