#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LccApiNet.Model {
    
    
    /// <summary>
    /// Indicates command that is sended to client controller to be executed by it.
    /// </summary>
    public class CommandName : SmartEnum<CommandName> {
        
        /// <summary>
        /// Client controller should decline league match.
        /// </summary>
        public static CommandName DeclineMatch = new CommandName("DeclineMatch", 1);
        
        /// <summary>
        /// Client controller should accept league match.
        /// </summary>
        public static CommandName AcceptMatch = new CommandName("AcceptMatch", 2);
        
        /// <summary>
        /// Test
        /// </summary>
        public static CommandName SomeParametrized = new CommandName("SomeParametrized", 3);
        
        public CommandName(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
