#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Indicates command that is sent to client controller to be executed by it.
    /// </summary>
    public class CommandName : SmartEnum<CommandName> {
        
        /// <summary>
        /// Client controller should decline league match.
        /// </summary>
        public static CommandName DeclineMatch = new CommandName("DeclineMatch", 1);
        
        /// <summary>
        /// Client controller should accept league match.
        /// </summary>
        public static CommandName AcceptMatch = new CommandName("AcceptMatch", 2);
        
        /// <summary>
        /// Client controller should hover on champion in a champ select stage.
        /// </summary>
        public static CommandName HoverChampion = new CommandName("HoverChampion", 3);
        
        /// <summary>
        /// Client controller should complete current action by banning or picking a champion.
        /// </summary>
        public static CommandName CompleteAction = new CommandName("CompleteAction", 4);
        
        public CommandName(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
