//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LccApiNet.Model {
    
    
    /// <summary>
    /// Indicates phase of the game flow in league client.
    /// </summary>
    public class GameflowPhase : SmartEnum<GameflowPhase> {
        
        /// <summary>
        /// User wandering around client.
        /// </summary>
        public static GameflowPhase None = new GameflowPhase("None", 1);
        
        /// <summary>
        /// User in the lobby.
        /// </summary>
        public static GameflowPhase Lobby = new GameflowPhase("Lobby", 2);
        
        /// <summary>
        /// Matchmaking in progress.
        /// </summary>
        public static GameflowPhase Matchmaking = new GameflowPhase("Matchmaking", 3);
        
        /// <summary>
        /// 
        /// </summary>
        public static GameflowPhase CheckedIntoTournament = new GameflowPhase("CheckedIntoTournament", 4);
        
        /// <summary>
        /// User should accept or decline match.
        /// </summary>
        public static GameflowPhase ReadyCheck = new GameflowPhase("ReadyCheck", 5);
        
        /// <summary>
        /// User selecting and/or banning champions.
        /// </summary>
        public static GameflowPhase ChampSelect = new GameflowPhase("ChampSelect", 6);
        
        /// <summary>
        /// 
        /// </summary>
        public static GameflowPhase GameStart = new GameflowPhase("GameStart", 7);
        
        /// <summary>
        /// 
        /// </summary>
        public static GameflowPhase FailedToLaunch = new GameflowPhase("FailedToLaunch", 8);
        
        /// <summary>
        /// Game in progress.
        /// </summary>
        public static GameflowPhase InProgress = new GameflowPhase("InProgress", 9);
        
        /// <summary>
        /// 
        /// </summary>
        public static GameflowPhase Reconnect = new GameflowPhase("Reconnect", 10);
        
        /// <summary>
        /// Waiting for post game stats.
        /// </summary>
        public static GameflowPhase WaitingForStats = new GameflowPhase("WaitingForStats", 11);
        
        /// <summary>
        /// When game is ended but user has not returned to the lobby yet.
        /// </summary>
        public static GameflowPhase PreEndOfGame = new GameflowPhase("PreEndOfGame", 12);
        
        /// <summary>
        /// Game is ended.
        /// </summary>
        public static GameflowPhase EndOfGame = new GameflowPhase("EndOfGame", 13);
        
        /// <summary>
        /// 
        /// </summary>
        public static GameflowPhase TerminatedInError = new GameflowPhase("TerminatedInError", 14);
        
        public GameflowPhase(string name, int value) : 
                base(name, value) {
        }
    }
}
