#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// 
    /// </summary>
    public class ActionRequestedParameters {
        
        /// <summary>
        /// When this action was requested by league client.
        /// </summary>
        [JsonProperty("requestedAt")]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.UnixDateTimeConverter))]
        public DateTime RequestedAt { get; set; } = default!;
        
        /// <summary>
        /// Is action is prescribed for an ally or an opponent.
        /// </summary>
        [JsonProperty("isAllyAction")]
        public bool IsAllyAction { get; set; } = default!;
        
        /// <summary>
        /// Specifies range of actors the action was requested from ([0..4]).
        /// </summary>
        [JsonProperty("actorsRange")]
        public ValueRange ActorsRange { get; set; } = default!;
        
        /// <summary>
        /// Type of the action.
        /// </summary>
        [JsonProperty("type")]
        [JsonConverter(typeof(SmartEnumNameConverter<ActionType, int>))]
        public ActionType Type { get; set; } = default!;
        
        public ActionRequestedParameters(DateTime requestedAt, bool isAllyAction, ValueRange actorsRange, ActionType type) {
            this.RequestedAt = requestedAt;
            this.IsAllyAction = isAllyAction;
            this.ActorsRange = actorsRange;
            this.Type = type;
        }
    }
}

#nullable restore
