#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// 
    /// </summary>
    public class ChampionHoveredParameters {
        
        /// <summary>
        /// Position of the actor in ally or enemy team ([0..4]).
        /// </summary>
        [JsonProperty("actorPosition")]
        public int ActorPosition { get; set; } = default!;
        
        /// <summary>
        /// Whether actor is on ally or enemy team.
        /// </summary>
        [JsonProperty("isActorAnAlly")]
        public bool IsActorAnAlly { get; set; } = default!;
        
        /// <summary>
        /// ID of the hovered champion.
        /// </summary>
        [JsonProperty("championId")]
        public int ChampionId { get; set; } = default!;
        
        public ChampionHoveredParameters(int actorPosition, bool isActorAnAlly, int championId) {
            this.ActorPosition = actorPosition;
            this.IsActorAnAlly = isActorAnAlly;
            this.ChampionId = championId;
        }
    }
}

#nullable restore
