#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Parameters of the /client/reportChampSelectStarted method.
    /// </summary>
    public class ChampSelectParameters {
        
        /// <summary>
        /// Index of the user in allies array.
        /// </summary>
        [JsonProperty("userPosition")]
        public int UserPosition { get; set; } = default!;
        
        /// <summary>
        /// Count of matched enemies.
        /// </summary>
        [JsonProperty("enemiesCount")]
        public int EnemiesCount { get; set; } = default!;
        
        /// <summary>
        /// Array of matched allies' roles
        /// </summary>
        [JsonProperty("alliesRoles")]
        public List<Role> AlliesRoles { get; set; } = default!;
        
        public ChampSelectParameters(int userPosition, int enemiesCount, List<Role> alliesRoles) {
            this.UserPosition = userPosition;
            this.EnemiesCount = enemiesCount;
            this.AlliesRoles = alliesRoles;
        }
    }
}

#nullable restore
