#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Parameters of the /client/reportChampSelectStarted method.
    /// </summary>
    public class ChampSelectParameters {
        
        /// <summary>
        /// Index of the user in allies array.
        /// </summary>
        [JsonProperty("userPosition")]
        public int UserPosition { get; set; } = default!;
        
        /// <summary>
        /// Type of the queue for which the pick stage was started.
        /// </summary>
        [JsonProperty("queueType")]
        [JsonConverter(typeof(SmartEnumNameConverter<QueueType, int>))]
        public QueueType QueueType { get; set; } = default!;
        
        /// <summary>
        /// Whether bans are intended for chosen game mode.
        /// </summary>
        [JsonProperty("bansPlanned")]
        public bool BansPlanned { get; set; } = default!;
        
        /// <summary>
        /// Count of matched enemies.
        /// </summary>
        [JsonProperty("enemiesCount")]
        public int EnemiesCount { get; set; } = default!;
        
        /// <summary>
        /// Array of matched allies' roles
        /// </summary>
        [JsonProperty("alliesRoles")]
        public List<Role> AlliesRoles { get; set; } = default!;
        
        /// <summary>
        /// List of champions that user owns.
        /// </summary>
        [JsonProperty("availableChampions")]
        public List<int> AvailableChampions { get; set; } = default!;
        
        public ChampSelectParameters(int userPosition, QueueType queueType, bool bansPlanned, int enemiesCount, List<Role> alliesRoles, List<int> availableChampions) {
            this.UserPosition = userPosition;
            this.QueueType = queueType;
            this.BansPlanned = bansPlanned;
            this.EnemiesCount = enemiesCount;
            this.AlliesRoles = alliesRoles;
            this.AvailableChampions = availableChampions;
        }
    }
}

#nullable restore
