#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Parameters of /client/sendCommand method.
    /// </summary>
    public class SendCommandParameters {
        
        /// <summary>
        /// Determine which controller should execute this command.
        /// </summary>
        [JsonProperty("controllerId")]
        public int ControllerId { get; set; } = default!;
        
        /// <summary>
        /// Command that should be sent to the client controller.
        /// </summary>
        [JsonProperty("commandName")]
        [JsonConverter(typeof(SmartEnumNameConverter<CommandName, int>))]
        public CommandName CommandName { get; set; } = default!;
        
        /// <summary>
        /// Arguments of the command.
        /// </summary>
        [JsonProperty("commandArgs")]
        public SomeParametrizedCommandArgs? CommandArgs { get; set; }//;
        
        public SendCommandParameters(int controllerId, CommandName commandName, SomeParametrizedCommandArgs? commandArgs) {
            this.ControllerId = controllerId;
            this.CommandName = commandName;
            this.CommandArgs = commandArgs;
        }
    }
}

#nullable restore
