//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LccApiNet;
using LccApiNet.Categories.Abstraction;
using LccApiNet.Exceptions;
using LccApiNet.Model;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;


namespace LccApiNet.Categories {
    
    
    /// <inheritdoc />
    public class DeviceCategory : IDeviceCategory {
        
        private ILccApi _api;
        
        public DeviceCategory(ILccApi api) {
            this._api = api;
        }
        
        /// <inheritdoc />
        public async Task<List<Device>> GetDevicesAsync(CancellationToken token = default)
        {
            DevicesResponse response = await _api.ExecuteAsync<DevicesResponse>("/device/getDevices", true, token).ConfigureAwait(false);
            return response.Devices;
        }
        
        /// <inheritdoc />
        public async Task<Device> GetDeviceByIdAsync(int deviceId, CancellationToken token = default)
        {
            DeviceResponse response = await _api.ExecuteAsync<DeviceResponse, int>("/device/getDeviceById", "deviceId", deviceId, true, token).ConfigureAwait(false);
            return response.Device;
        }
        
        /// <inheritdoc />
        public async Task ChangeDeviceNameAsync(string name, CancellationToken token = default) {
            // <auto-generated-safe-area> Code within tag borders shouldn't be harmful and won't cause incorrect behavior except you are very dumb.
            // TODO: Add parameters validation
            // </auto-generated-safe-area>
            ChangeNameParameters parameters = new ChangeNameParameters(name);
            await this._api.ExecuteAsync<ChangeNameParameters>("/device/changeDeviceName", parameters, true, token);
        }
        
        /// <inheritdoc />
        public async Task<List<ClientController>> GetControllersAsync([Optional] CancellationToken token)
        {
            ControllersResponse response = await _api.ExecuteAsync<ControllersResponse>("/device/getControllers", true, token).ConfigureAwait(false);
            return response.Controllers;
        }
        
        /// <inheritdoc />
        public async Task<ClientController> GetControllerByIdAsync(int controllerId, CancellationToken token = default)
        {
            ControllerResponse response = await _api.ExecuteAsync<ControllerResponse, int>("/device/getControllerById", "controllerId", controllerId, true, token).ConfigureAwait(false);
            return response.Controller;
        }
        
        /// <inheritdoc />
        public async Task ChangeControllerNameAsync(string name, CancellationToken token = default) {
            // <auto-generated-safe-area> Code within tag borders shouldn't be harmful and won't cause incorrect behavior except you are very dumb.
            // TODO: Add parameters validation
            // </auto-generated-safe-area>
            ChangeNameParameters parameters = new ChangeNameParameters(name);
            await this._api.ExecuteAsync<ChangeNameParameters>("/device/changeControllerName", parameters, true, token);
        }
    }
}
