#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LccApiNet;
using LccApiNet.Categories.Abstraction;
using LccApiNet.Exceptions;
using LccApiNet.Model;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;


namespace LccApiNet.Categories {
    
    
    /// <inheritdoc />
    public class IdentityCategory : IIdentityCategory {
        
        private ILccApi _api;
        
        public IdentityCategory(ILccApi api) {
            this._api = api;
        }
        
        /// <inheritdoc />
        public async Task<bool> LoginAsync(LoginParameters @params, bool saveCredentials = false, CancellationToken token = default)
        {
            try {
                string response = await _api.ExecuteAsync<string, LoginParameters>("/identity/login", @params, "accessToken", false, token).ConfigureAwait(false);
                if (response == null)
                    throw new WrongResponseException("/identity/login");

                await _api.UpdateAccessToken(response, saveCredentials).ConfigureAwait(false);
                return true;
            } catch (MethodException me) {
                if (me.ErrorName == MethodError.WrongNicknameEmailOrPassword) {
                    return false;
                } else {
                    throw me;
                }
            }
        }
        
        /// <inheritdoc />
        public async Task<ProfileInfo> GetProfileInfoAsync(CancellationToken token = default)
        {
            ProfileInfoResponse response = await _api.ExecuteAsync<ProfileInfoResponse>("/identity/getProfileInfo", true, token).ConfigureAwait(false);
            return response.Profile;
        }
        
        /// <inheritdoc />
        public async Task RefreshAccessTokenAsync(CancellationToken token = default)
        {
            string? response = await _api.ExecuteAsync<string?>("/identity/refreshAccessToken", "accessToken", true, token).ConfigureAwait(false);
            if (response == null)
                throw new WrongResponseException("/identity/login");

            await _api.UpdateAccessToken(response).ConfigureAwait(false);
        }
    }
}

#nullable restore
