#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Response of the /identity/register method.
    /// </summary>
    public class RegistrationResponse : ApiResponse {
        
        /// <summary>
        /// ID of the user that has been registered.
        /// Used to confirm account.
        /// </summary>
        [JsonProperty("registeredId")]
        public int RegisteredId { get; set; } = default!;
    }
}

#nullable restore
