//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LccApiNet.Model {
    
    
    /// <summary>
    /// Indicates what error occurred during execution of the command.
    /// </summary>
    public class CommandError : SmartEnum<CommandError> {
        
        /// <summary>
        /// Occurs when executing commands 'AcceptMatch' and 'DeclineMatch' if current game flow phase is not 'ReadyCheck'.
        /// </summary>
        public static CommandError ReadyCheckError = new CommandError("ReadyCheckError", 1);
        
        public CommandError(string name, int value) : 
                base(name, value) {
        }
    }
}
