#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Specifies value range borders.
    /// Used for taking values from an array.
    /// Values count is {@see entitiesCount} and they are taken from {@see firstIndex},
    /// so the range is from {@see firstIndex} to {@see firstIndex} + {@see entitiesCount}.
    /// </summary>
    public class ValueRange {
        
        /// <summary>
        /// Index of the first element of the array that needs to be taking.
        /// </summary>
        [JsonProperty("firstIndex")]
        public int FirstIndex { get; set; } = default!;
        
        /// <summary>
        /// How many elements needs to be taken.
        /// </summary>
        [JsonProperty("entitiesCount")]
        public int EntitiesCount { get; set; } = default!;
    }
}

#nullable restore
