#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LccApiNet.Model;
using LccApiNet.Services;


namespace LccApiNet.EventHandlers {
    
    
    /// <summary>
    /// Represents a function that will handle <see cref="EventService.OnClientEvent"/> event.
    /// </summary>
    public delegate void ClientEventHandler(object sender, ClientEvent args);
}

#nullable restore
