#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LccApiNet.Model {
    
    
    /// <summary>
    /// Result of the method execution.
    /// </summary>
    public class ExecutionResult : SmartEnum<ExecutionResult> {
        
        /// <summary>
        /// 
        /// </summary>
        public static ExecutionResult Okay = new ExecutionResult("Okay", 1);
        
        /// <summary>
        /// 
        /// </summary>
        public static ExecutionResult Error = new ExecutionResult("Error", 2);
        
        public ExecutionResult(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
