//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LccApiNet.Model {
    
    
    /// <summary>
    /// 
    /// </summary>
    public class MethodError : SmartEnum<MethodError> {
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError InternalServerError = new MethodError("InternalServerError", 1);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError WrongApiKey = new MethodError("WrongApiKeyError", 2);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError WrongAccessToken = new MethodError("WrongAccessTokenError", 3);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError AccessTokenNotProvided = new MethodError("AccessTokenNotProvidedError", 4);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError WrongNicknameEmailOrPassword = new MethodError("WrongNicknameEmailOrPasswordError", 5);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError JsonParsing = new MethodError("JsonParsingError", 6);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError MissingMethodParameters = new MethodError("MissingMethodParametersError", 7);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError InvalidCommandParameters = new MethodError("InvalidCommandParametersError", 8);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError InvalidMethodParameter = new MethodError("InvalidMethodParameterError", 9);
        
        /// <summary>
        /// 
        /// </summary>
        public static MethodError ListenerIsAlreadyRegistered = new MethodError("ListenerIsAlreadyRegisteredError", 10);
        
        public MethodError(string name, int value) : 
                base(name, value) {
        }
    }
}
