#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Parameters of the /identity/confirm method.
    /// </summary>
    public class ConfirmationParameters {
        
        /// <summary>
        /// ID of an account that should be confirmed.
        /// </summary>
        [JsonProperty("accountId")]
        public int AccountId { get; set; } = default!;
        
        /// <summary>
        /// 6-digits code to confirm account.
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; } = default!;
        
        /// <summary>
        /// Name of the device that will be authorized under the user.
        /// </summary>
        [JsonProperty("deviceName")]
        public string DeviceName { get; set; } = default!;
        
        /// <summary>
        /// Type of the device that will be authorized under the user.
        /// </summary>
        [JsonProperty("deviceType")]
        [JsonConverter(typeof(SmartEnumNameConverter<DeviceType, int>))]
        public DeviceType DeviceType { get; set; } = default!;
        
        public ConfirmationParameters(int accountId, string code, string deviceName, DeviceType deviceType) {
            this.AccountId = accountId;
            this.Code = code;
            this.DeviceName = deviceName;
            this.DeviceType = deviceType;
        }
    }
}

#nullable restore
