#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Parameters of the /identity/login method. 
    ///Contains api key, id of the type of the authorizing device
    ///and user credentials
    /// </summary>
    public class LoginParameters {
        
        /// <summary>
        /// User's email or username
        /// </summary>
        [JsonProperty("login")]
        public string Login { get; set; } = default!;
        
        /// <summary>
        /// User's password
        /// </summary>
        [JsonProperty("password")]
        public string Password { get; set; } = default!;
        
        /// <summary>
        /// Name of the device that will be authorized under the user
        /// </summary>
        [JsonProperty("deviceName")]
        public string DeviceName { get; set; } = default!;
        
        /// <summary>
        /// Type of the device that will be authorized under the user
        /// </summary>
        [JsonProperty("deviceType")]
        [JsonConverter(typeof(SmartEnumNameConverter<DeviceType, int>))]
        public DeviceType DeviceType { get; set; } = default!;
        
        public LoginParameters(string login, string password, string deviceName, DeviceType deviceType) {
            this.Login = login;
            this.Password = password;
            this.DeviceName = deviceName;
            this.DeviceType = deviceType;
        }
    }
}

#nullable restore
