#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Parameters of the /identity/register method.
    /// </summary>
    public class RegisterParameters {
        
        /// <summary>
        /// Name of the user that will be registered.
        /// </summary>
        [JsonProperty("username")]
        public string Username { get; set; } = default!;
        
        /// <summary>
        /// Email of the user that will be registered.
        /// </summary>
        [JsonProperty("email")]
        public string Email { get; set; } = default!;
        
        /// <summary>
        /// User's password
        /// </summary>
        [JsonProperty("password")]
        public string Password { get; set; } = default!;
        
        public RegisterParameters(string username, string email, string password) {
            this.Username = username;
            this.Email = email;
            this.Password = password;
        }
    }
}

#nullable restore
