#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Parameters of the /identity/resendConfirmation method.
    /// </summary>
    public class ResendConfirmationParameters {
        
        /// <summary>
        /// ID of an account that should be confirmed..
        /// </summary>
        [JsonProperty("accountId")]
        public int AccountId { get; set; } = default!;
        
        public ResendConfirmationParameters(int accountId) {
            this.AccountId = accountId;
        }
    }
}

#nullable restore
