#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LarcApiNet;
using LarcApiNet.Categories.Abstraction;
using LarcApiNet.Exceptions;
using LarcApiNet.Model;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;


namespace LarcApiNet.Categories {
    
    
    /// <inheritdoc />
    public class DeviceCategory : IDeviceCategory {
        
        private ILarcApi _api;
        
        public DeviceCategory(ILarcApi api) {
            _api = api;
        }
        
        /// <inheritdoc />
        public async Task<List<Device>> GetDevicesAsync(CancellationToken token = default) 
        {
        	DevicesResponse response = await _api.ExecuteAsync<DevicesResponse> ("/device/getDevices", true, token);
        	// <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
        	// TODO: Add response validation
        	// </auto-generated-safe-area>
        	return response.Devices;
        }
        
        /// <inheritdoc />
        public async Task<Device> GetDeviceByIdAsync(int id, CancellationToken token = default) 
        {
        	// <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
        	// TODO: Add parameters validation
        	// </auto-generated-safe-area>
        	GetByIdParameters parameters = new GetByIdParameters (id);
        	DeviceResponse response = await _api.ExecuteAsync<DeviceResponse, GetByIdParameters> ("/device/getDeviceById", parameters, true, token);
        	// <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
        	// TODO: Add response validation
        	// </auto-generated-safe-area>
        	return response.Device;
        }
        
        /// <inheritdoc />
        public async Task ChangeDeviceNameAsync(string name, CancellationToken token = default) 
        {
        	// <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
        	// TODO: Add parameters validation
        	// </auto-generated-safe-area>
        	ChangeNameParameters parameters = new ChangeNameParameters (name);
        	await _api.ExecuteAsync<ChangeNameParameters> ("/device/changeDeviceName", parameters, true, token);
        }
        
        /// <inheritdoc />
        public async Task<List<ClientController>> GetControllersAsync(CancellationToken token = default) 
        {
        	ControllersResponse response = await _api.ExecuteAsync<ControllersResponse> ("/device/getControllers", true, token);
        	// <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
        	// TODO: Add response validation
        	// </auto-generated-safe-area>
        	return response.Controllers;
        }
        
        /// <inheritdoc />
        public async Task<ClientController> GetControllerByIdAsync(int id, CancellationToken token = default) 
        {
        	// <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
        	// TODO: Add parameters validation
        	// </auto-generated-safe-area>
        	GetByIdParameters parameters = new GetByIdParameters (id);
            ControllerResponse controllerResponse = await _api.ExecuteAsync<ControllerResponse, GetByIdParameters>("/device/getControllerById", parameters, true, token);
            
            return controllerResponse.Controller;
        }
        
        /// <inheritdoc />
        public async Task ChangeControllerNameAsync(string name, CancellationToken token = default) 
        {
        	// <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
        	// TODO: Add parameters validation
        	// </auto-generated-safe-area>
        	ChangeNameParameters parameters = new ChangeNameParameters (name);
        	await _api.ExecuteAsync<ChangeNameParameters> ("/device/changeControllerName", parameters, true, token);
        }
    }
}

#nullable restore
