#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LccApiNet;
using LccApiNet.Categories.Abstraction;
using LccApiNet.Exceptions;
using LccApiNet.Model;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;


namespace LccApiNet.Categories {
    
    
    /// <inheritdoc />
    public class IdentityCategory : IIdentityCategory {
        
        private ILccApi _api;
        
        public IdentityCategory(ILccApi api) {
            _api = api;
        }
        
        /// <inheritdoc />
        public async Task<string> LoginAsync(string login, string password, string deviceName, DeviceType deviceType, CancellationToken token = default) {
            // <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
            // TODO: Add parameters validation
            // </auto-generated-safe-area>
            LoginParameters parameters = new LoginParameters(login, password, deviceName, deviceType);
            AccessTokenResponse response = await this._api.ExecuteAsync<AccessTokenResponse, LoginParameters>("/identity/login", parameters, false, token);
            // <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
            // TODO: Add response validation
            // </auto-generated-safe-area>
            return response.AccessToken;
        }
        
        /// <inheritdoc />
        public async Task<ProfileInfo> GetProfileInfoAsync(CancellationToken token = default) 
        {
        	ProfileInfoResponse response = await _api.ExecuteAsync<ProfileInfoResponse> ("/identity/getProfileInfo", true, token).ConfigureAwait (false);
        	return response.Profile;
        }
        
        /// <inheritdoc />
        public async Task<string> RefreshAccessTokenAsync(CancellationToken token = default) {
            AccessTokenResponse response = await this._api.ExecuteAsync<AccessTokenResponse>("/identity/refreshAccessToken", true, token);
            // <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved.
            // TODO: Add response validation
            // </auto-generated-safe-area>
            return response.AccessToken;
        }
    }
}

#nullable restore
