#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LarcApiNet.Model;
using LarcApiNet.Services;


namespace LarcApiNet.EventHandlers {
    
    
    /// <summary>
    /// Represents a function that will handle <see cref="EventService.OnCommandEvent"/> event.
    /// </summary>
    public delegate void CommandEventHandler(object sender, CommandEvent args);
}

#nullable restore
