#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Type of the client event.
    /// </summary>
    public class ClientEventType : SmartEnum<ClientEventType> {
        
        /// <summary>
        /// Client was opened. Gameflow phase changed to {@see GameflowPhase.None}.
        /// </summary>
        public static ClientEventType ClientOpened = new ClientEventType("ClientOpened", 1);
        
        /// <summary>
        /// Client was closed.
        /// </summary>
        public static ClientEventType ClientClosed = new ClientEventType("ClientClosed", 2);
        
        /// <summary>
        /// Client game glow phase was changed.
        /// </summary>
        public static ClientEventType GameflowPhaseChanged = new ClientEventType("GameflowPhaseChanged", 3);
        
        public ClientEventType(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
