#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Describes an event related to the client.
    /// </summary>
    public class ClientEvent {
        
        /// <summary>
        /// Type of the event.
        /// </summary>
        [JsonProperty("type")]
        [JsonConverter(typeof(SmartEnumNameConverter<ClientEventType, int>))]
        public ClientEventType Type { get; set; } = default!;
        
        /// <summary>
        /// Contains id of the client that reported about client changes.
        /// </summary>
        [JsonProperty("controllerId")]
        public int ControllerId { get; set; } = default!;
        
        /// <summary>
        /// If gameflow phase is changed, contains new gameflow phase value.
        /// </summary>
        [JsonProperty("gameflowPhase")]
        [JsonConverter(typeof(SmartEnumNameConverter<GameflowPhase, int>))]
        public GameflowPhase? GameflowPhase { get; set; }//;
        
        /// <summary>
        /// If gameflow phase is changed to {@see GameflowPhase.ReadyCheck},
        /// contains timestamp when ready check was initiated.
        /// </summary>
        [JsonProperty("readyCheckStarted")]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.UnixDateTimeConverter))]
        public DateTime? ReadyCheckStarted { get; set; }//;
    }
}

#nullable restore
