#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Type of the event.
    /// Specify how event message should be deserialized.
    /// </summary>
    public class EventType : SmartEnum<EventType> {
        
        /// <summary>
        /// Event message should be deserialized as <see cref="DeviceEvent"/>
        /// </summary>
        public static EventType Device = new EventType("Device", 1);
        
        /// <summary>
        /// Event message should be deserialized as <see cref="ClientEvent"/>
        /// </summary>
        public static EventType Client = new EventType("Client", 2);
        
        /// <summary>
        /// Event message should be deserialized as <see cref="PickEvent"/>
        /// </summary>
        public static EventType Pick = new EventType("Pick", 3);
        
        /// <summary>
        /// Event message should be deserialized as <see cref="CommandEvent"/>
        /// </summary>
        public static EventType Command = new EventType("Command", 4);
        
        public EventType(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
