#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Describes an event related to champ select phase in league client.
    /// </summary>
    public class PickEvent {
        
        /// <summary>
        /// Type of the event
        /// </summary>
        [JsonProperty("type")]
        [JsonConverter(typeof(SmartEnumNameConverter<PickEventType, int>))]
        public PickEventType Type { get; set; } = default!;
        
        /// <summary>
        /// ID of the controller that manipulates league client
        /// in which this champ select phase is happening.
        /// </summary>
        [JsonProperty("controllerId")]
        public int ControllerId { get; set; } = default!;
        
        /// <summary>
        /// Contains initial pick stage info when it's started.
        /// Only if {@see type} is {@see PickEventType.ChampSelectStarted}, otherwise null.
        /// </summary>
        [JsonProperty("stage")]
        public PickStage? Stage { get; set; }//;
        
        /// <summary>
        /// When the action was requested.
        /// Only if {@see type} is {@see PickEventType.ActionRequested}, otherwise null.
        /// </summary>
        [JsonProperty("requestedAt")]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.UnixDateTimeConverter))]
        public DateTime? RequestedAt { get; set; }//;
        
        /// <summary>
        /// How much time user have to complete the action in seconds
        /// before he will be thrown out of queue.
        /// Only if {@see type} is {@see PickEventType.ActionRequested}, otherwise null.
        /// </summary>
        [JsonProperty("timeToAct")]
        public int? TimeToAct { get; set; }//;
        
        /// <summary>
        /// Specifies if requested or changed action was pick or ban.
        /// Only if {@see type} is {@see PickEventType.ActionRequested}, otherwise null.
        /// </summary>
        [JsonProperty("actionType")]
        [JsonConverter(typeof(SmartEnumNameConverter<ActionType, int>))]
        public ActionType? ActionType { get; set; }//;
        
        /// <summary>
        /// Specifies range of actors the action was requested from ([0..4]).
        /// Only if {@see type} is {@see PickEventType.ActionRequested}, otherwise null.
        /// </summary>
        [JsonProperty("actorsRange")]
        public ValueRange? ActorsRange { get; set; }//;
        
        /// <summary>
        /// Position of the summoner in ally or enemy team ([0..4]).
        /// Only if {@see type} is champion related or {@see PickEventType.SkinChanged},
        /// otherwise null.
        /// </summary>
        [JsonProperty("actorPosition")]
        public int? SummonerPosition { get; set; }//;
        
        /// <summary>
        /// Is summoner in ally or enemy team.
        /// Only if {@see type} is champion related, otherwise null.
        /// </summary>
        [JsonProperty("isSummonerAnAlly")]
        public bool? IsSummonerAnAlly { get; set; }//;
        
        /// <summary>
        /// ID of a champion that was banned, picked or hovered on.
        /// Only if {@see type} is {@see PickEventType.ChampionHovered} or optional if {@see PickEventType.ActionCompleted},
        /// otherwise null.
        /// </summary>
        [JsonProperty("championId")]
        public int? ChampionId { get; set; }//;
        
        /// <summary>
        /// ID of a skin that was applied to the picked champion.
        /// Only if {@see type} is {@see PickEventType.SkinChanged}, otherwise null.
        /// </summary>
        [JsonProperty("skinId")]
        public int? SkinId { get; set; }//;
    }
}

#nullable restore
