#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Represents a «League of Legends» client
    /// that is controlled by a client controller.
    /// </summary>
    public class LeagueClient : BindableBase {
        
        private GameflowPhase? _gameflowPhase;
        
        private DateTime? _readyCheckStarted;
        
        /// <summary>
        /// Describes champ select phase.
        /// </summary>
        [JsonProperty("pick")]
        public PickStage? Pick { get; set; }//;
        
        /// <summary>
        /// Gameflow phase of the client.
        /// </summary>
        [JsonProperty("gameflowPhase")]
        [JsonConverter(typeof(SmartEnumNameConverter<GameflowPhase, int>))]
        public GameflowPhase? GameflowPhase {
            get {
                return _gameflowPhase;
            }
            set {
                this.SetProperty(ref _gameflowPhase, value);
            }
        }
        
        /// <summary>
        /// Time when ready check was initiated.
        /// </summary>
        [JsonProperty("readyCheckStarted")]
        [JsonConverter(typeof(UnixDateTimeConverter))]
        public DateTime? ReadyCheckStarted {
            get {
                return _readyCheckStarted;
            }
            set {
                this.SetProperty(ref _readyCheckStarted, value);
            }
        }
    }
}

#nullable restore
