#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Represents select phase in league client
    /// with the data about teams, summoners, champions, bans etc.
    /// </summary>
    public class PickStage : BindableBase {
        
        /// <summary>
        /// Index of the allies array that corresponds to the user.
        /// </summary>
        [JsonProperty("userPosition")]
        public int UserPosition { get; set; } = default!;
        
        private bool _bansPlanned = default!;
        
        private DateTime? _actionRequestedAt;
        
        /// <summary>
        /// Members of the user's team.
        /// Index in the array points to player position in the pick order.
        /// </summary>
        [JsonProperty("allies")]
        public List<Summoner> Allies { get; set; } = default!;
        
        /// <summary>
        /// Members of an opposing team.
        /// Index in the array points to player position in the pick order.
        /// </summary>
        [JsonProperty("enemies")]
        public List<Summoner> Enemies { get; set; } = default!;
        
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty("bansPlanned")]
        public bool BansPlanned {
            get {
                return _bansPlanned;
            }
            set {
                this.SetProperty(ref _bansPlanned, value);
            }
        }
        
        /// <summary>
        /// Time when the last action was requested from summoner(s).
        /// </summary>
        [JsonProperty("actionRequestedAt")]
        [JsonConverter(typeof(UnixDateTimeConverter))]
        public DateTime? ActionRequestedAt {
            get {
                return _actionRequestedAt;
            }
            set {
                this.SetProperty(ref _actionRequestedAt, value);
            }
        }
    }
}

#nullable restore
