#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Queue type of pick stage.
    /// Determines the rules of the game and rules for the pick stage.
    /// </summary>
    public class QueueType : SmartEnum<QueueType> {
        
        /// <summary>
        /// 
        /// </summary>
        public static QueueType Custom = new QueueType("Custom", 1);
        
        /// <summary>
        /// 
        /// </summary>
        public static QueueType DraftPick = new QueueType("DraftPick", 2);
        
        /// <summary>
        /// 
        /// </summary>
        public static QueueType RankedSolo = new QueueType("RankedSolo", 3);
        
        /// <summary>
        /// 
        /// </summary>
        public static QueueType BlindPick = new QueueType("BlindPick", 4);
        
        /// <summary>
        /// 
        /// </summary>
        public static QueueType RankedFlex = new QueueType("RankedFlex", 5);
        
        public QueueType(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
