#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Indicates player role in the «League of Legends».
    /// </summary>
    public class Role : SmartEnum<Role> {
        
        /// <summary>
        /// 
        /// </summary>
        public static Role Top = new Role("Top", 1);
        
        /// <summary>
        /// 
        /// </summary>
        public static Role Jungle = new Role("Jungle", 2);
        
        /// <summary>
        /// 
        /// </summary>
        public static Role Middle = new Role("Middle", 3);
        
        /// <summary>
        /// 
        /// </summary>
        public static Role Bottom = new Role("Bottom", 4);
        
        /// <summary>
        /// 
        /// </summary>
        public static Role Support = new Role("Support", 5);
        
        /// <summary>
        /// 
        /// </summary>
        public static Role Any = new Role("Any", 6);
        
        public Role(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
