#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum.JsonNet;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


namespace LarcApiNet.Model {
    
    
    /// <summary>
    /// Represents a player in the «League of Legends»
    /// as an ally or opponent in the champ select phase
    /// </summary>
    public class Summoner : BindableBase {
        
        /// <summary>
        /// Role that this summoner has been assigned after matchmaking.
        /// </summary>
        [JsonProperty("assignedRole")]
        [JsonConverter(typeof(SmartEnumNameConverter<Role, int>))]
        public Role AssignedRole { get; set; } = default!;
        
        private int _pickedChampionId = default!;
        
        private int _bannedChampionId = default!;
        
        private bool _pickCompleted = default!;
        
        private bool _banCompleted = default!;
        
        private int _skinId = default!;
        
        private ActionType? _actionInProgressType;
        
        /// <summary>
        /// ID of the champion this summoner picked.
        /// </summary>
        [JsonProperty("pickedChampionId")]
        public int PickedChampionId {
            get {
                return _pickedChampionId;
            }
            set {
                this.SetProperty(ref _pickedChampionId, value);
            }
        }
        
        /// <summary>
        /// ID of the champion this summoner banned.
        /// </summary>
        [JsonProperty("bannedChampionId")]
        public int BannedChampionId {
            get {
                return _bannedChampionId;
            }
            set {
                this.SetProperty(ref _bannedChampionId, value);
            }
        }
        
        /// <summary>
        /// Whether summoner actually picked a champion or only hovered it.
        /// </summary>
        [JsonProperty("pickCompleted")]
        public bool PickCompleted {
            get {
                return _pickCompleted;
            }
            set {
                this.SetProperty(ref _pickCompleted, value);
            }
        }
        
        /// <summary>
        /// Whether summoner actually banned a champion or only hovered it.
        /// </summary>
        [JsonProperty("banCompleted")]
        public bool BanCompleted {
            get {
                return _banCompleted;
            }
            set {
                this.SetProperty(ref _banCompleted, value);
            }
        }
        
        /// <summary>
        /// ID of the skin of a picked champion.
        /// </summary>
        [JsonProperty("skinId")]
        public int SkinId {
            get {
                return _skinId;
            }
            set {
                this.SetProperty(ref _skinId, value);
            }
        }
        
        /// <summary>
        /// Specifies type of action the summoner participates in.
        /// </summary>
        [JsonProperty("actionInProgressType")]
        [JsonConverter(typeof(SmartEnumNameConverter<ActionType, int>))]
        public ActionType? ActionInProgressType {
            get {
                return _actionInProgressType;
            }
            set {
                this.SetProperty(ref _actionInProgressType, value);
            }
        }
    }
}

#nullable restore
