#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ardalis.SmartEnum;


namespace LccApiNet.Model {
    
    
    /// <summary>
    /// Indicates type of the device that user owns.
    /// </summary>
    public class DeviceType : SmartEnum<DeviceType> {
        
        /// <summary>
        /// 
        /// </summary>
        public static DeviceType Controller = new DeviceType("Controller", 1);
        
        /// <summary>
        /// 
        /// </summary>
        public static DeviceType Phone = new DeviceType("Phone", 2);
        
        public DeviceType(string name, int value) : 
                base(name, value) {
        }
    }
}

#nullable restore
